#!/usr/bin/env python3
"""Materialize KernelBench problems as farmerbob task directories.

Bead farmerbob-pxh: fetch KernelBench and materialize its problems as task
directories under the exp-contract shape, preserving upstream problem ids so
results stay comparable to published numbers.

    shims/kb_ingest.py --level 1 --out tasks/kernelbench
    shims/kb_ingest.py --level 1 --only 19_ReLU --out tasks/kernelbench

Layout per problem (exp-contract shape):
    level1/19_ReLU/
        task.toml       name, description, verification, timeouts, scoring config
        setup.sh        one-time env prep (checks kb-env + KB_SRC; cached)
        verify.sh       correctness -> stdout JSON {"correct": bool, "detail": ...}
        bench.sh        measurement  -> stdout JSON {"ms": float, "metrics": {...}}
        ref/
            problem.py      upstream source, verbatim
            upstream.json   {level, problem_id, name, code_hash}
        candidate.py    what the agent edits; starts as a copy of the reference
                        (correct, speedup 1.0) so an untouched task measures
                        instead of failing.

Task names are `kernelbench:level<level>/<stem>`, e.g.
`kernelbench:level1/19_ReLU`, matching the bead's `fb task add` naming.
"""

import argparse
import hashlib
import os
import pathlib
import re
import stat
import sys

KB_LEVEL_DIR = "/home/gabe/KernelBench/KernelBench/level{level}"
KB_ENV_PYTHON = os.path.expanduser("~/.local/share/farmerbob/kb-env/bin/python")
REPO = pathlib.Path(__file__).resolve().parent.parent
KB_SHIM = REPO / "shims" / "kb_shim.py"


def _code_hash(code: str) -> str:
    cleaned = re.sub(r'"""[\s\S]*?"""|\'\'\'[\s\S]*?\'\'\'', "", code)
    cleaned = re.sub(r"#.*$|\s+", "", cleaned, flags=re.MULTILINE)
    return hashlib.md5(cleaned.encode()).hexdigest()


def _task_toml(name: str, description: str) -> str:
    return (
        f"name = \"{name}\"\n"
        f"description = \"{description}\"\n"
        "verification = \"Benchmark\"\n"
        "timeout_s = 600\n"
        "exclusive = [\"gpu\"]\n"
        "min_trials = 3\n"
    )


def _script(python: str, shim: pathlib.Path, verb: str, extra: str = "") -> str:
    return (
        "#!/bin/sh\n"
        "# Generated by shims/kb_ingest.py. Runs the candidate in candidate.py\n"
        "# against the reference in ref/problem.py via the kb eval bridge.\n"
        "# Stdout carries one JSON object; exit codes follow the bench contract:\n"
        "# verify exits 0 whenever the instrument ran (even for a wrong kernel),\n"
        "# bench exits 0 only with a measurement.\n"
        f"HERE=$(dirname \"$0\")\n"
        f"PY=\"{python}\"\n"
        f"command -v \"$PY\" >/dev/null 2>&1 || PY=\"python3\"\n"
        f"exec \"$PY\" \"{shim}\" {verb} --ref \"$HERE/ref/problem.py\""
        f" --candidate \"$HERE/candidate.py\"{extra}\n"
    )


_SETUP_SH = """#!/bin/sh
# One-time environment prep (cached). Verifies the benchmark toolchain exists.
# The kb-env virtualenv reuses the system torch (pinned by fingerprint) and
# carries the lightweight eval deps; the LLM inference stack is stubbed by
# the shim, never installed.
KB_ENV="$HOME/.local/share/farmerbob/kb-env/bin/python"
if [ -x "$KB_ENV" ]; then
    "$KB_ENV" -c "import torch, tqdm, pydantic, dotenv; assert torch.cuda.is_available()" 2>/dev/null && exit 0
fi
echo "setup: kb-env python missing or cuda unavailable (expected $KB_ENV)" >&2
exit 1
"""


def ingest(level: int, out: pathlib.Path, only: str | None) -> int:
    src_dir = pathlib.Path(KB_LEVEL_DIR.format(level=level))
    if not src_dir.is_dir():
        print(f"ingest: level dir not found: {src_dir}", file=sys.stderr)
        return 2
    level_out = out / f"level{level}"
    count = 0
    for problem in sorted(src_dir.glob("*.py")):
        stem = problem.stem
        if only and only not in (stem, problem.name):
            continue
        code = problem.read_text()
        # Upstream id is the numeric prefix: "19_ReLU" -> 19.
        match = re.match(r"(\d+)_", stem)
        problem_id = int(match.group(1)) if match else 0
        task_dir = level_out / stem
        task_dir.mkdir(parents=True, exist_ok=True)
        name = f"kernelbench:level{level}/{stem}"
        (task_dir / "task.toml").write_text(
            _task_toml(name, f"KernelBench level {level} problem {stem}")
        )
        (task_dir / "setup.sh").write_text(_SETUP_SH)
        (task_dir / "verify.sh").write_text(
            _script(KB_ENV_PYTHON, KB_SHIM, "verify", " --trials 1")
        )
        (task_dir / "bench.sh").write_text(
            _script(KB_ENV_PYTHON, KB_SHIM, "bench", " --perf-trials 10")
        )
        for script in ("setup.sh", "verify.sh", "bench.sh"):
            path = task_dir / script
            path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
        ref_dir = task_dir / "ref"
        ref_dir.mkdir(exist_ok=True)
        (ref_dir / "problem.py").write_text(code)
        upstream = (
            "{\n"
            f'  "level": {level},\n'
            f'  "problem_id": {problem_id},\n'
            f'  "name": "{stem}",\n'
            f'  "code_hash": "{_code_hash(code)}"\n'
            "}\n"
        )
        (ref_dir / "upstream.json").write_text(upstream)
        if not (task_dir / "candidate.py").exists():
            (task_dir / "candidate.py").write_text(code)
        count += 1
    print(f"ingested {count} problems from level {level} into {level_out}")
    return 0 if count else 1


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Ingest KernelBench as farmerbob tasks")
    parser.add_argument("--level", type=int, required=True, choices=(1, 2, 3))
    parser.add_argument("--out", required=True)
    parser.add_argument("--only", default=None)
    args = parser.parse_args(argv)
    return ingest(args.level, pathlib.Path(args.out), args.only)


if __name__ == "__main__":
    sys.exit(main())
