#!/usr/bin/env bash
# Install this repository's git hooks, and keep beads' hooks running underneath them.
#
# WHY IT IS SHAPED LIKE THIS. beads sets core.hooksPath to .beads/hooks and MANAGES the files
# there -- it rewrites .beads/hooks/pre-commit whenever it likes. A section appended after its
# "END BEADS INTEGRATION" marker was silently erased within minutes, and the commit that
# followed went in unformatted while everything reported success. Editing a file another tool
# regenerates is not installation.
#
# So this takes ownership of core.hooksPath and forwards to beads rather than living inside it.
# Each hook here runs the beads hook of the same name first, with the same arguments, and fails
# if it fails -- beads keeps working, and it can regenerate its own directory as often as it
# likes without touching ours.
set -euo pipefail
cd "$(dirname "$0")/.."
REPO=$(pwd)
BEADS="$REPO/.beads/hooks"
HOOKS="$REPO/hooks"

# Forward every hook beads has, plus pre-commit whether or not beads has one.
names=$(ls "$BEADS" 2>/dev/null | grep -v '^\.' || true)
names=$(printf '%s\npre-commit\n' "$names" | sort -u | grep -v '^$')

for n in $names; do
  # pre-commit gets the rustfmt gate appended after the forward; everything else is pure forward.
  {
    echo '#!/usr/bin/env bash'
    echo "# Generated by hooks/install.sh. Owns core.hooksPath so beads cannot regenerate over it."
    echo 'set -uo pipefail'
    echo "beads=\"$BEADS/$n\""
    echo '[ -x "$beads" ] && { "$beads" "$@" || exit $?; }'
    if [ "$n" = pre-commit ]; then
      echo "\"$HOOKS/pre-commit-fmt\" || exit 1"
    fi
    echo 'exit 0'
  } > "$HOOKS/$n"
  chmod +x "$HOOKS/$n"
done

git config core.hooksPath hooks
echo "core.hooksPath -> hooks"
echo "forwarding to beads: $(echo $names | tr '\n' ' ')"
